import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Download, FileText, Plus, Save, Sparkles, Trash2, Upload, Wand2 } from 'lucide-react'
import './index.css'

const API = '/api'
const api = async (path, options = {}) => {
  const headers = options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }
  const r = await fetch(`${API}${path}`, { headers, ...options })
  if (!r.ok) throw new Error(await r.text())
  return r.json()
}
const templates = ['classic', 'modern', 'executive', 'technical', 'minimal', 'two-column', 'corporate', 'ats-optimized']
const blankResume = {
  contact: { name: '', title: '', email: '', phone: '', linkedin: '', portfolio: '', location: '' },
  summary: '', skills: [['', '', '']], technical: {}, experience: [], education: [], certifications: [], additional: [], custom_sections: []
}
const safe = (v) => String(v || '').replace(/<[^>]+>/g, '')

function App() {
  const [page, setPage] = useState('dashboard')
  const [resumes, setResumes] = useState([])
  const [current, setCurrent] = useState(null)
  const load = () => api('/resumes').then(r => { setResumes(r); if (current && !r.find(x => x.id === current.id)) setCurrent(null) })
  useEffect(() => { load() }, [])
  return <div className="min-h-screen">
    <header className="sticky top-0 z-20 border-b border-white/10 bg-[#06070d]/80 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
        <div><h1 className="text-2xl font-black">Resume & Career Document Builder</h1><p className="text-sm text-slate-400">Premium self-hosted career tooling</p></div>
        <nav className="flex flex-wrap gap-2">{[['dashboard', 'Dashboard'], ['editor', 'Resume Builder'], ['cover', 'Cover Letter'], ['thanks', 'Thank You'], ['roles', 'Role Builder']].map(x => <button key={x[0]} onClick={() => setPage(x[0])} className={`btn ${page === x[0] ? 'btn-primary' : ''}`}>{x[1]}</button>)}</nav>
      </div>
    </header>
    <main className="mx-auto max-w-7xl px-6 py-8">
      {page === 'dashboard' && <Dashboard resumes={resumes} setCurrent={setCurrent} setPage={setPage} reload={load} />}
      {page === 'editor' && (current ? <Editor resume={current} setResume={setCurrent} reload={load} /> : <EmptyEditor setCurrent={setCurrent} setPage={setPage} reload={load} />)}
      {page === 'cover' && (current ? <Cover resume={current} /> : <NeedResume />)}
      {page === 'thanks' && <ThankYou />}
      {page === 'roles' && <RoleBuilder setCurrent={setCurrent} setPage={setPage} />}
    </main>
  </div>
}

function Dashboard({ resumes, setCurrent, setPage, reload }) {
  const [importReview, setImportReview] = useState(null)
  async function upload(e) { const f = e.target.files[0]; if (!f) return; const fd = new FormData(); fd.append('file', f); const r = await fetch('/api/upload', { method: 'POST', body: fd }); if (!r.ok) { alert(await r.text()); return } setImportReview(await r.json()); e.target.value = '' }
  async function loadSample() { const r = await api('/sample-resume', { method: 'POST' }); await reload(); setCurrent(r); setPage('editor') }
  async function del(e, id) { e.stopPropagation(); if (!confirm('Delete this saved document?')) return; await api(`/resumes/${id}`, { method: 'DELETE' }); await reload() }
  async function confirmImport(template = 'modern') { const r = await api('/import-confirm', { method: 'POST', body: JSON.stringify({ filename: importReview.filename, template, data: importReview.parsed }) }); setImportReview(null); await reload(); setCurrent(r); setPage('editor') }
  return <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
    <section className="space-y-6">
      <div className="glass p-6">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div><h2 className="text-3xl font-black">Saved documents</h2><p className="text-slate-400">Dashboard: saved documents and intake tools. The editor lives under Resume Builder. Complicated, apparently.</p></div>
          <div className="flex flex-wrap gap-2"><button className="btn" onClick={loadSample}>Load Sample Resume</button><label className="btn btn-primary cursor-pointer"><Upload className="mr-2 inline h-4 w-4" />Upload Resume<input type="file" className="hidden" accept=".pdf,.doc,.docx" onChange={upload} /></label></div>
        </div>
        {resumes.length === 0 ? <div className="mt-10 rounded-3xl border border-dashed border-white/15 p-10 text-center text-slate-400"><FileText className="mx-auto mb-3 h-10 w-10 text-orange-300" />No saved documents. Use Resume Builder for a blank resume, upload one here, or build from description below.</div> : <div className="mt-6 grid gap-4 md:grid-cols-2">{resumes.map(r => <button key={r.id} onClick={() => { setCurrent(r); setPage('editor') }} className="glass relative p-5 text-left hover:border-orange-400"><button className="absolute right-3 top-3 rounded-full bg-red-500/15 p-2 text-red-300 hover:bg-red-500/30" onClick={(e) => del(e, r.id)} title="Delete"><Trash2 className="h-4 w-4" /></button><div className="text-xs uppercase tracking-[.2em] text-orange-300">{r.template}</div><h3 className="mt-2 pr-10 text-xl font-black">{r.name}</h3><p className="mt-1 text-slate-400">{r.title}</p><p className="mt-4 text-xs text-slate-500">Last edited {new Date(r.updated_at).toLocaleString()}</p></button>)}</div>}
      </div>
      <BuildFromDescription setCurrent={setCurrent} setPage={setPage} reload={reload} />
    </section>
    <aside className="glass p-6"><h3 className="text-xl font-black">Portfolio-ready</h3><p className="mt-2 text-slate-400">Live preview, ATS targeting, DOCX/PDF exports, Claude-assisted tailoring, upload review, and eight distinct templates.</p><div className="mt-6 space-y-3 text-sm text-slate-300"><p>• Blank resumes start with template selection</p><p>• Upload review: original left, parsed right</p><p>• AI Build from Description intake</p><p>• Delete cards with confirmation</p></div></aside>
    {importReview && <ImportReview review={importReview} onCancel={() => setImportReview(null)} onConfirm={confirmImport} />}
  </div>
}
function NeedResume() { return <div className="glass p-8 text-center text-slate-300">Create, upload, or load a resume first.</div> }
function EmptyEditor({ setCurrent, setPage, reload }) { return <TemplatePicker setCurrent={setCurrent} setPage={setPage} reload={reload} /> }

function TemplatePicker({ setCurrent, setPage, reload }) {
  async function create(template) { const r = await api('/resumes', { method: 'POST', body: JSON.stringify({ name: 'Untitled Resume', title: 'New Resume', template, data: structuredClone(blankResume) }) }); await reload(); setCurrent(r); setPage('editor') }
  return <div className="glass p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-3xl font-black">Blank Resume — choose a template</h2><p className="text-slate-400">Pick one of eight templates, then the editor opens with a blank resume. Yes, the button now does something.</p></div><button className="btn" onClick={() => setPage('dashboard')}>Back to Dashboard</button></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{templates.map(t => <button key={t} onClick={() => create(t)} className="glass p-4 text-left hover:border-orange-400"><div className="mb-3 text-xs uppercase tracking-[.2em] text-orange-300">{t}</div><div className={`template-thumb resume-${t}`}><div className="thumb-header"></div><div className="thumb-line w-4/5"></div><div className="thumb-line w-3/5"></div><div className="thumb-section"></div><div className="thumb-line"></div><div className="thumb-line w-5/6"></div><div className="thumb-section"></div><div className="thumb-line w-4/6"></div></div></button>)}</div></div>
}

function ImportReview({ review, onCancel, onConfirm }) {
  const [template, setTemplate] = useState('modern')
  return <div className="fixed inset-0 z-50 overflow-auto bg-black/80 p-6 backdrop-blur"><div className="mx-auto max-w-7xl"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-3xl font-black">Review uploaded resume</h2><p className="text-slate-400">Original extraction on the left. Parsed editable resume on the right. Confirm before saving, because blindly trusting parsers is how HR software happened.</p></div><div className="flex gap-2"><select className="input w-56" value={template} onChange={e => setTemplate(e.target.value)}>{templates.map(t => <option key={t}>{t}</option>)}</select><button className="btn" onClick={onCancel}>Cancel</button><button className="btn btn-primary" onClick={() => onConfirm(template)}>Confirm Import</button></div></div><div className="grid gap-5 lg:grid-cols-2"><pre className="glass max-h-[78vh] overflow-auto whitespace-pre-wrap p-5 text-sm text-slate-200 scrollbar">{review.original_text}</pre><div className="max-h-[78vh] overflow-auto scrollbar"><ResumePreview data={review.parsed} setData={() => { }} template={template} /></div></div></div></div>
}

function BuildFromDescription({ setCurrent, setPage, reload }) {
  const [f, setF] = useState({ title: '', years: '', skills: '', employer_role: '', education: '', achievements: '', target: '', tone: 'modern', template: 'modern' })
  const [busy, setBusy] = useState(false)
  const set = (k, v) => setF({ ...f, [k]: v })
  async function build() { if (!f.title.trim()) { alert('Current or target job title is required'); return } setBusy(true); try { const r = await api('/build-from-description', { method: 'POST', body: JSON.stringify(f) }); await reload(); setCurrent(r); setPage('editor') } finally { setBusy(false) } }
  return <section className="glass p-6"><h2 className="text-2xl font-black">Build from Description</h2><p className="mt-1 text-slate-400">Personalized AI resume generation from real background details. Separate from the generic Role Builder.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Input label="Current or target job title" v={f.title} on={v => set('title', v)} /><Input label="Years of experience" v={f.years} on={v => set('years', v)} /><Input label="Most recent employer and role" v={f.employer_role} on={v => set('employer_role', v)} /><Input label="Education" v={f.education} on={v => set('education', v)} /><Input label="Target role/industry" v={f.target} on={v => set('target', v)} /><label className="mb-2 block text-sm text-slate-400">Tone preference<select className="input mt-1" value={f.tone} onChange={e => set('tone', e.target.value)}><option>formal</option><option>modern</option><option>technical</option></select></label><label className="mb-2 block text-sm text-slate-400 md:col-span-2">Key skills and technologies<textarea className="input mt-1 h-24" value={f.skills} onChange={e => set('skills', e.target.value)} /></label><label className="mb-2 block text-sm text-slate-400 md:col-span-2">Key achievements or projects<textarea className="input mt-1 h-28" value={f.achievements} onChange={e => set('achievements', e.target.value)} /></label></div><div className="mt-3 flex items-center gap-3"><select className="input w-56" value={f.template} onChange={e => set('template', e.target.value)}>{templates.map(t => <option key={t}>{t}</option>)}</select><button className="btn btn-primary" onClick={build} disabled={busy}>{busy ? 'Building...' : 'Build Personalized Resume'}</button></div></section>
}

function Editor({ resume, setResume, reload }) {
  const [data, setData] = useState(resume.data)
  const [template, setTemplate] = useState(resume.template || 'modern')
  const [job, setJob] = useState('')
  const [tailor, setTailor] = useState(null)
  useEffect(() => { setData(resume.data); setTemplate(resume.template || 'modern') }, [resume.id])
  const set = (path, val) => { const d = structuredClone(data); let o = d; path.slice(0, -1).forEach(k => o = o[k]); o[path.at(-1)] = val; setData(d) }
  async function save() { const r = await api(`/resumes/${resume.id}`, { method: 'PUT', body: JSON.stringify({ name: (data.contact.name || 'Untitled') + ' Resume', title: data.contact.title || 'Resume', template, data }) }); setResume(r); reload() }
  async function dup() { const r = await api(`/resumes/${resume.id}/duplicate`, { method: 'POST' }); setResume(r); reload() }
  async function analyze() { setTailor(await api('/tailor', { method: 'POST', body: JSON.stringify({ resume_id: resume.id, job_description: job }) })) }
  return <div className="grid gap-6 xl:grid-cols-[560px_1fr]">
    <section className="glass max-h-[calc(100vh-130px)] overflow-auto p-5 scrollbar">
      <div className="flex flex-wrap gap-2"><button className="btn btn-primary" onClick={save}><Save className="mr-1 inline h-4 w-4" />Save</button><button className="btn" onClick={dup}>Save Version</button><a className="btn" href={`/api/resumes/${resume.id}/export/docx`}><Download className="mr-1 inline h-4 w-4" />DOCX</a><a className="btn" href={`/api/resumes/${resume.id}/export/pdf`}>PDF</a></div>
      <label className="mt-4 block text-sm text-slate-400">Template</label><select className="input mt-1" value={template} onChange={e => setTemplate(e.target.value)}>{templates.map(t => <option key={t}>{t}</option>)}</select>
      <Section title="Contact Info"><Input label="Name" v={data.contact.name} on={v => set(['contact', 'name'], v)} /><Input label="Title" v={data.contact.title} on={v => set(['contact', 'title'], v)} /><Input label="Email" v={data.contact.email} on={v => set(['contact', 'email'], v)} /><Input label="Phone" v={data.contact.phone} on={v => set(['contact', 'phone'], v)} /><Input label="LinkedIn" v={data.contact.linkedin} on={v => set(['contact', 'linkedin'], v)} /><Input label="Portfolio" v={data.contact.portfolio} on={v => set(['contact', 'portfolio'], v)} /><Input label="Location" v={data.contact.location} on={v => set(['contact', 'location'], v)} /></Section>
      <Section title="Professional Summary"><RichText value={data.summary} onChange={v => set(['summary'], v)} /></Section>
      <Skills data={data} setData={setData} />
      <Technical data={data} setData={setData} />
      <Experience data={data} setData={setData} />
      <Education data={data} setData={setData} />
      <List title="Certifications" items={data.certifications || []} setItems={x => set(['certifications'], x)} />
      <List title="Additional Experience" items={data.additional || []} setItems={x => set(['additional'], x)} />
      <CustomSections data={data} setData={setData} />
      <Section title="Job-targeted resume mode"><textarea className="input h-32" placeholder="Paste job description" value={job} onChange={e => setJob(e.target.value)} /><button className="btn btn-primary mt-2" onClick={analyze}><Sparkles className="mr-1 inline h-4 w-4" />Analyze ATS Fit</button>{tailor && <div className="mt-3 rounded-xl bg-black/30 p-3"><div className="text-2xl font-black text-orange-300">ATS {tailor.ats_score}%</div><p className="mt-2 text-sm">Missing keywords: {tailor.missing_keywords.join(', ') || 'None obvious'}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{tailor.suggestions}</p></div>}</Section>
    </section>
    <section className="overflow-auto scrollbar"><ResumePreview data={data} setData={setData} template={template} /></section>
  </div>
}
function Section({ title, children }) { return <div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="mb-3 font-black text-orange-300">{title}</h3>{children}</div> }
function Input({ label, v, on, type = 'text' }) { return <label className="mb-2 block text-sm text-slate-400">{label}<input type={type} className="input mt-1" value={v || ''} onChange={e => on(e.target.value)} /></label> }
function RichText({ value, onChange }) { return <div><div className="mb-2 flex gap-2"><button className="btn" onMouseDown={e => { e.preventDefault(); document.execCommand('bold') }}>Bold</button><button className="btn" onMouseDown={e => { e.preventDefault(); document.execCommand('italic') }}>Italic</button></div><div className="input min-h-28" contentEditable suppressContentEditableWarning dangerouslySetInnerHTML={{ __html: value || '' }} onBlur={e => onChange(e.currentTarget.innerHTML)} /></div> }
function List({ title, items, setItems, rich = false }) { const update = (i, v) => setItems(items.map((x, n) => n === i ? v : x)); const move = (i, d) => { const a = [...items], j = i + d; if (j < 0 || j >= a.length) return;[a[i], a[j]] = [a[j], a[i]]; setItems(a) }; return <Section title={title}>{items.map((x, i) => <div className="mb-2 flex gap-2" key={i}>{rich ? <div className="flex-1"><RichText value={x} onChange={v => update(i, v)} /></div> : <textarea className="input h-16" value={x} onChange={e => update(i, e.target.value)} />}<button className="btn" onClick={() => move(i, -1)}>↑</button><button className="btn" onClick={() => move(i, 1)}>↓</button><button className="btn" onClick={() => setItems(items.filter((_, n) => n !== i))}>×</button></div>)}<button className="btn" onClick={() => setItems([...items, ''])}><Plus className="mr-1 inline h-4 w-4" />Add</button></Section> }
function Skills({ data, setData }) { const rows = data.skills || []; const setCell = (i, j, v) => { const r = rows.map(row => [...row]); r[i][j] = v; setData({ ...data, skills: r }) }; const addChip = (i, v) => { if (!v.trim()) return; const r = rows.map(row => [...row]); const idx = r[i].findIndex(x => !x); if (idx >= 0) r[i][idx] = v.trim(); else r[i].push(v.trim()); setData({ ...data, skills: r.map(x => (x.concat(['', '', ''])).slice(0, 3)) }) }; return <Section title="Areas of Expertise"><p className="mb-3 text-sm text-slate-400">Edit chips or table cells. Three columns render in the preview. Blank cells no longer masquerade as competence.</p>{rows.map((row, i) => <div key={i} className="mb-3 rounded-xl bg-black/20 p-3"><div className="mb-2 flex flex-wrap gap-2">{row.filter(Boolean).map((chip, j) => <span key={j} className="rounded-full bg-orange-500/15 px-3 py-1 text-sm text-orange-200">{chip}<button className="ml-2" onClick={() => setCell(i, j, '')}>×</button></span>)}</div><div className="grid gap-2 md:grid-cols-3">{[0, 1, 2].map(j => <input key={j} className="input" placeholder={`Column ${j + 1}`} value={row[j] || ''} onChange={e => setCell(i, j, e.target.value)} />)}</div><div className="mt-2 flex gap-2"><input className="input" placeholder="Add chip" onKeyDown={e => { if (e.key === 'Enter') { addChip(i, e.currentTarget.value); e.currentTarget.value = '' } }} /><button className="btn" onClick={() => setData({ ...data, skills: rows.filter((_, n) => n !== i) })}>Remove row</button></div></div>)}<button className="btn" onClick={() => setData({ ...data, skills: [...rows, ['', '', '']] })}>Add expertise row</button></Section> }
function Technical({ data, setData }) { const entries = Object.entries(data.technical || {}); const update = (oldK, k, v) => { const t = { ...data.technical }; delete t[oldK]; t[k] = v; setData({ ...data, technical: t }) }; return <Section title="Technical Proficiencies">{entries.map(([k, v]) => <div className="mb-2 grid gap-2 md:grid-cols-[160px_1fr_auto]" key={k}><input className="input" value={k} onChange={e => update(k, e.target.value, v)} /><input className="input" value={v} onChange={e => update(k, k, e.target.value)} /><button className="btn" onClick={() => { const t = { ...data.technical }; delete t[k]; setData({ ...data, technical: t }) }}>×</button></div>)}<button className="btn" onClick={() => setData({ ...data, technical: { ...(data.technical || {}), Category: '' } })}>Add proficiency</button></Section> }
function Experience({ data, setData }) { const jobs = data.experience || []; const setJobs = experience => setData({ ...data, experience }); const [drag, setDrag] = useState(null); const moveJob = (from, to) => { if (from === null || to === null || from === to) return; const a = [...jobs]; const [x] = a.splice(from, 1); a.splice(to, 0, x); setJobs(a) }; return <Section title="Career Experience">{jobs.map((j, idx) => <div key={idx} draggable onDragStart={() => setDrag(idx)} onDragOver={e => e.preventDefault()} onDrop={() => moveJob(drag, idx)} className="mb-5 rounded-xl bg-black/20 p-3"><div className="mb-2 cursor-move text-xs uppercase tracking-[.2em] text-slate-500">Drag position #{idx + 1}</div><div className="grid gap-2 md:grid-cols-2"><Input label="Title" v={j.title} on={v => { const a = [...jobs]; a[idx].title = v; setJobs(a) }} /><Input label="Company" v={j.company} on={v => { const a = [...jobs]; a[idx].company = v; setJobs(a) }} /><Input label="Location" v={j.location} on={v => { const a = [...jobs]; a[idx].location = v; setJobs(a) }} /><Input label="Start date" type="month" v={j.start_date} on={v => { const a = [...jobs]; a[idx].start_date = v; a[idx].dates = `${v || ''} – ${a[idx].end_date || ''}`; setJobs(a) }} /><Input label="End date" type="month" v={j.end_date} on={v => { const a = [...jobs]; a[idx].end_date = v; a[idx].dates = `${a[idx].start_date || ''} – ${v || ''}`; setJobs(a) }} /></div><List title="Bullet points" rich items={j.bullets || []} setItems={items => { const a = [...jobs]; a[idx].bullets = items; setJobs(a) }} /><button className="btn" onClick={() => setJobs(jobs.filter((_, n) => n !== idx))}>Remove Position</button></div>)}<button className="btn" onClick={() => setJobs([...jobs, { title: '', company: '', location: '', start_date: '', end_date: '', dates: '', bullets: [''] }])}>Add Position</button></Section> }
function Education({ data, setData }) { const items = data.education || []; return <Section title="Education">{items.map((e, i) => <div className="mb-3 grid gap-2 md:grid-cols-3" key={i}><input className="input" placeholder="Degree" value={e.degree || ''} onChange={ev => { const a = [...items]; a[i].degree = ev.target.value; setData({ ...data, education: a }) }} /><input className="input" placeholder="School" value={e.school || ''} onChange={ev => { const a = [...items]; a[i].school = ev.target.value; setData({ ...data, education: a }) }} /><input className="input" placeholder="Details" value={e.details || ''} onChange={ev => { const a = [...items]; a[i].details = ev.target.value; setData({ ...data, education: a }) }} /></div>)}<button className="btn" onClick={() => setData({ ...data, education: [...items, { degree: '', school: '', details: '' }] })}>Add Education</button></Section> }
function CustomSections({ data, setData }) { const sections = data.custom_sections || []; return <Section title="Custom Sections">{sections.map((s, i) => <div className="mb-4 rounded-xl bg-black/20 p-3" key={i}><Input label="Section title" v={s.title} on={v => { const a = [...sections]; a[i].title = v; setData({ ...data, custom_sections: a }) }} /><List title="Bullets" items={s.bullets || []} setItems={items => { const a = [...sections]; a[i].bullets = items; setData({ ...data, custom_sections: a }) }} /><button className="btn" onClick={() => setData({ ...data, custom_sections: sections.filter((_, n) => n !== i) })}>Remove Custom Section</button></div>)}<button className="btn" onClick={() => setData({ ...data, custom_sections: [...sections, { title: 'Custom Section', bullets: [''] }] })}>Add Custom Section</button></Section> }

function Editable({ children, onSave, className = '', tag: Tag = 'span' }) { return <Tag className={className} contentEditable suppressContentEditableWarning onBlur={e => onSave(safe(e.currentTarget.innerHTML))}>{children}</Tag> }
function ResumePreview({ data, setData, template }) {
  const c = data.contact || {}; const two = template === 'two-column'; const ats = template === 'ats-optimized'
  const setContact = (k, v) => setData({ ...data, contact: { ...data.contact, [k]: v } })
  const setSummary = v => setData({ ...data, summary: v })
  const setBullet = (i, j, v) => { const experience = [...data.experience]; experience[i].bullets[j] = v; setData({ ...data, experience }) }
  const content = <><H template={template}>Professional Summary</H><Editable tag="p" onSave={setSummary}>{safe(data.summary)}</Editable><H template={template}>Areas of Expertise</H>{ats ? <p>{(data.skills || []).flat().filter(Boolean).join(' • ')}</p> : <table className="w-full border-collapse text-sm"><tbody>{(data.skills || []).map((r, i) => <tr key={i}>{[0, 1, 2].map(n => <td className="border border-gray-300 p-2" key={n}>{r[n] || ''}</td>)}</tr>)}</tbody></table>}<H template={template}>Technical Proficiencies</H>{Object.entries(data.technical || {}).map(([k, v]) => <p key={k} className="text-sm"><b>{k}:</b> {v}</p>)}<H template={template}>Career Experience</H>{(data.experience || []).map((j, i) => <div key={i} className="mb-4"><div className="flex justify-between gap-4 font-bold"><span>{j.title} — {j.company}, {j.location}</span><span>{j.dates}</span></div><ul className="ml-5 list-disc text-sm">{(j.bullets || []).map((b, n) => <li key={n}><Editable onSave={v => setBullet(i, n, v)}>{safe(b)}</Editable></li>)}</ul></div>)}<H template={template}>Education</H>{(data.education || []).map((e, i) => <p key={i}><b>{e.degree}</b>, {e.school} — {e.details}</p>)}<H template={template}>Certifications</H><p>{(data.certifications || []).join(' • ')}</p><H template={template}>Additional Experience</H>{(data.additional || []).map((a, i) => <p key={i}>{a}</p>)}{(data.custom_sections || []).map((s, i) => <div key={i}><H template={template}>{s.title}</H><ul className="ml-5 list-disc">{(s.bullets || []).map((b, n) => <li key={n}>{b}</li>)}</ul></div>)}</>
  if (two) return <div className={`resume-page resume-${template} grid grid-cols-[250px_1fr] gap-8`}><aside className="bg-slate-900 p-5 text-white"><h1 className="text-3xl font-black">{c.name}</h1><p>{c.title}</p><H template={template}>Contact</H><p>{c.email}</p><p>{c.phone}</p><p>{c.location}</p><H template={template}>Skills</H><p>{(data.skills || []).flat().filter(Boolean).join(' • ')}</p><H template={template}>Certifications</H><p>{(data.certifications || []).join(' • ')}</p></aside><main>{content}</main></div>
  return <div className={`resume-page resume-${template}`}><div className="resume-header grid grid-cols-[1fr_auto] gap-6 pb-5"><div><Editable tag="h1" className="text-4xl font-black uppercase tracking-tight" onSave={v => setContact('name', v)}>{c.name || 'Your Name'}</Editable><Editable tag="p" className="mt-1 block text-lg font-semibold text-gray-700" onSave={v => setContact('title', v)}>{c.title || 'Target Title'}</Editable></div><div className="text-right text-sm text-gray-700"><p>{c.email}</p><p>{c.phone}</p><p>{c.location}</p><p>{c.linkedin}</p><p>{c.portfolio}</p></div></div>{content}</div>
}
function H({ children, template }) { return <h2 className={`mt-5 mb-2 text-sm font-black uppercase tracking-[.18em] ${template === 'ats-optimized' ? 'text-black' : 'text-orange-600'}`}>{children}</h2> }

function Cover({ resume }) { const [company, setCompany] = useState(''), [manager, setManager] = useState('Hiring Manager'), [job, setJob] = useState(''), [doc, setDoc] = useState(null); async function gen() { setDoc(await api('/cover-letter', { method: 'POST', body: JSON.stringify({ resume_id: resume.id, company, hiring_manager: manager, job_description: job }) })) } return <Builder title="Cover Letter Builder" icon={FileText}><Input label="Company" v={company} on={setCompany} /><Input label="Hiring Manager" v={manager} on={setManager} /><textarea className="input mt-2 h-40" placeholder="Job description" value={job} onChange={e => setJob(e.target.value)} /><button className="btn btn-primary mt-3" onClick={gen}><Wand2 className="mr-1 inline h-4 w-4" />Generate</button>{doc && <DocEditor doc={doc} />}</Builder> }
function ThankYou() { const [f, setF] = useState({ interviewer: '', company: '', position: '', interview_date: '', talking_points: '' }), [doc, setDoc] = useState(null); async function gen() { setDoc(await api('/thank-you', { method: 'POST', body: JSON.stringify(f) })) } return <Builder title="Thank You Letter Builder" icon={FileText}>{Object.keys(f).map(k => <Input key={k} label={k.replaceAll('_', ' ')} v={f[k]} on={v => setF({ ...f, [k]: v })} />)}<button className="btn btn-primary mt-3" onClick={gen}>Generate</button>{doc && <DocEditor doc={doc} />}</Builder> }
function RoleBuilder({ setCurrent, setPage }) { const [roles, setRoles] = useState({}), [title, setTitle] = useState('Senior Network Administrator'), [industry, setIndustry] = useState('Information Technology'), [built, setBuilt] = useState(null); useEffect(() => { api('/roles').then(setRoles) }, []); async function build() { setBuilt(await api('/role-build', { method: 'POST', body: JSON.stringify({ title, industry }) })) } async function saveDraft() { const r = await api('/resumes', { method: 'POST', body: JSON.stringify({ name: `${title} Draft`, title, template: 'modern', data: built.resume }) }); setCurrent(r); setPage('editor') } return <div className="grid gap-6 lg:grid-cols-[420px_1fr]"><section className="glass p-6"><h2 className="text-2xl font-black">Position / Role Builder</h2><Input label="Target industry" v={industry} on={setIndustry} /><Input label="Selected title" v={title} on={setTitle} /><button className="btn btn-primary mt-2" onClick={build}>Build Resume Draft</button><div className="mt-4 max-h-[560px] overflow-auto scrollbar">{Object.entries(roles).map(([cat, rs]) => <div key={cat} className="mb-4"><h3 className="font-bold text-orange-300">{cat}</h3>{rs.map(r => <button key={r.title} onClick={() => setTitle(r.title)} className="mb-1 mr-1 rounded-full border border-white/10 px-3 py-1 text-sm hover:border-orange-400">{r.below_target ? '⚠ ' : ''}{r.title}</button>)}</div>)}</div></section><section>{built && <><div className="mb-4 flex justify-end"><button className="btn btn-primary" onClick={saveDraft}>Save Draft & Edit</button></div><ResumePreview data={built.resume} setData={() => { }} template="modern" /></>}</section></div> }
function Builder({ title, icon: Icon, children }) { return <div className="glass mx-auto max-w-4xl p-6"><h2 className="text-3xl font-black"><Icon className="mr-2 inline h-7 w-7 text-orange-400" />{title}</h2><div className="mt-5">{children}</div></div> }
function DocEditor({ doc }) { const [content, setContent] = useState(doc.data.content); return <div className="mt-5"><textarea className="input h-96 whitespace-pre-wrap" value={content} onChange={e => setContent(e.target.value)} /><div className="mt-3 flex gap-2"><button className="btn">Editable Draft</button><button className="btn" onClick={() => navigator.clipboard.writeText(content)}>Copy</button></div></div> }

createRoot(document.getElementById('root')).render(<App />)
